"""criar tabela convites_usuarios

Revision ID: 19e146eeff4a
Revises: 6fac70d72d5e
Create Date: 2025-06-09 02:29:10.334209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19e146eeff4a'
down_revision: Union[str, None] = '6fac70d72d5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('convites_usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expira_em', sa.DateTime(), nullable=False),
    sa.Column('usado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_convites_usuarios_id'), 'convites_usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_convites_usuarios_token'), 'convites_usuarios', ['token'], unique=True)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_index(op.f('ix_convites_usuarios_token'), table_name='convites_usuarios')
    op.drop_index(op.f('ix_convites_usuarios_id'), table_name='convites_usuarios')
    op.drop_table('convites_usuarios')
    # ### end Alembic commands ###
