"""criar tabela empresa

Revision ID: 4afeb0a90374
Revises: 24ce976e8784
Create Date: 2025-06-25 18:48:20.348694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4afeb0a90374'
down_revision: Union[str, None] = '24ce976e8784'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hoteis', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.create_foreign_key(None, 'orcamentos_pre_pago', 'users', ['created_by_user_id'], ['id'])
    op.alter_column('roles', 'nome',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_roles_nome'), table_name='roles')
    op.add_column('users', sa.Column('data_nascimento', sa.Date(), nullable=True))
    op.alter_column('users', 'senha',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'senha',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'data_nascimento')
    op.create_index(op.f('ix_roles_nome'), 'roles', ['nome'], unique=1)
    op.alter_column('roles', 'nome',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'orcamentos_pre_pago', type_='foreignkey')
    op.alter_column('hoteis', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    # ### end Alembic commands ###
