"""add asaas_status and log_integracao

Revision ID: 6fac70d72d5e
Revises: 9b20c7d5c4a5
Create Date: 2025-06-03 16:01:48.497985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fac70d72d5e'
down_revision: Union[str, None] = '9b20c7d5c4a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_integracao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('mensagem', sa.Text(), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('resposta', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_integracao_id'), 'log_integracao', ['id'], unique=False)
    op.add_column('users', sa.Column('asaas_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'asaas_status')
    op.drop_index(op.f('ix_log_integracao_id'), table_name='log_integracao')
    op.drop_table('log_integracao')
    # ### end Alembic commands ###
