"""add data_nascimento to users

Revision ID: dd0422e3968e
Revises: 4b2571e06490
Create Date: 2025-06-23 19:28:07.421943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd0422e3968e'
down_revision: Union[str, None] = '4b2571e06490'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('orcamentos_pre_pago', sa.Column('descricao_parcelamento', sa.String(), nullable=True))
    op.add_column('orcamentos_pre_pago', sa.Column('created_by_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orcamentos_pre_pago', 'users', ['created_by_user_id'], ['id'])
    op.alter_column('roles', 'nome',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_roles_nome'), table_name='roles')
    op.add_column('users', sa.Column('data_nascimento', sa.Date(), nullable=True))
    op.alter_column('users', 'senha',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'senha',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'data_nascimento')
    op.create_index(op.f('ix_roles_nome'), 'roles', ['nome'], unique=1)
    op.alter_column('roles', 'nome',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'orcamentos_pre_pago', type_='foreignkey')
    op.drop_column('orcamentos_pre_pago', 'created_by_user_id')
    op.drop_column('orcamentos_pre_pago', 'descricao_parcelamento')
    op.alter_column('hoteis', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    # ### end Alembic commands ###
