"""criar tabela empresa

Revision ID: df6bf1d6a07e
Revises: 4afeb0a90374
Create Date: 2025-06-25 18:54:52.915862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df6bf1d6a07e'
down_revision: Union[str, None] = '4afeb0a90374'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
  
    sa.Column('razao_social', sa.String(), nullable=False),
    sa.Column('nome_fantasia', sa.String(), nullable=False),
    sa.Column('cnpj', sa.String(), nullable=True),
    sa.Column('cep', sa.String(), nullable=True),
    sa.Column('logradouro', sa.String(), nullable=True),
    sa.Column('numero', sa.String(), nullable=True),
    sa.Column('bairro', sa.String(), nullable=True),
    sa.Column('municipio', sa.String(), nullable=True),
    sa.Column('uf', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    
  
   
    op.alter_column('roles', 'nome',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_roles_nome'), table_name='roles')
    op.add_column('users', sa.Column('data_nascimento', sa.Date(), nullable=True))
    op.alter_column('users', 'senha',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'senha',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'data_nascimento')
    op.create_index(op.f('ix_roles_nome'), 'roles', ['nome'], unique=1)
    op.alter_column('roles', 'nome',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'orcamentos_pre_pago', type_='foreignkey')
    op.alter_column('hoteis', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_index(op.f('ix_empresas_id'), table_name='empresas')
    op.drop_table('empresas')
    # ### end Alembic commands ###
